# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90c9559ec3b51b8c26fd44acf846c45e1816ad0042bdada2d9c699afb3e0b394dbb385b1cc64a8a19eaa1bf210af93dfcb6fb8635c1ecfa684bfe29dbc89904f

test:
  secret_key_base: 72dd6e6d7486a082bd1e3a4180cb16df58c3871a06ebf094bd664a6c3f43838829dae01e25197ecf4eb594416a549e19d07153c611d78ac3a956974dd6271321

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
